### ISSUE TITLE
Unable to increase ASG desired size: unable to increase ASG 

### ISSUE THREAD

**Issue by AmjadHussainSyed** [TwinProduction/aws-eks-asg-rolling-update-handler#16]
Hi,

I'm getting the following error where its stuck with the following error. 
```
Unable to increase ASG desired size: unable to increase ASG <ASGNAME> desired count to 7: ScalingActivityInProgress: Scaling activity 0ea5f0da-97c6-1d64-5127-43e061c16819 is in progress and blocks this action
	status code: 400, request id: 740c62cf-be5a-4dab-9e9d-466d3b8fd36f
```

ASG Status:  

1. Desired Instances: 7 
2. Current running instances: 7
3. Min: 6
4. Max: 15

it seems when desired instances and current running instances are equal its throwing this error.

The error went off when i manually increased the desired count to 9 and its starting rolling out the instances.

Please advice.

**Comment by TwinProduction** [comment]
Hello,

The error that you showed is an error that AWS returns. I suspect that perhaps it really did have recently scaled up or down, which means that the next execution would have worked.

**Comment by AmjadHussainSyed** [comment]
sorry for late reply.
the same message was showing continuously until i increased the desired instances from aws console

**Comment by TwinProduction** [comment]
The following error:
```
status code: 400, request id: 740c62cf-be5a-4dab-9e9d-466d3b8fd36f
```
comes directly from a request to AWS' API.

I really wish I could do something for you here, but unless you find a way to reproduce it, the only assumption I can make here is that AWS had a hiccup -- however improbable that sounds.

The only difference between `aws-eks-asg-rolling-update-handler` and the AWS console when it comes to increasing the desired instance count is that the former "honors the cooldown period", or as they documented it:
```go
// Indicates whether Amazon EC2 Auto Scaling waits for the cooldown period to
// complete before initiating a scaling activity to set your Auto Scaling group
// to its new capacity. By default, Amazon EC2 Auto Scaling does not honor the
// cooldown period during manual scaling activities.
HonorCooldown *bool `type:"boolean"`
```
